# Generated by Django 6.0 on 2026-01-06 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100)),
                ('house_description', models.CharField(max_length=1500)),
                ('house_location', models.CharField(max_length=500)),
                ('house_images', models.ImageField(upload_to='media')),
                ('house_price', models.CharField(max_length=30)),
                ('house_size', models.CharField(max_length=30)),
                ('house_rooms_no', models.CharField(max_length=30)),
                ('house_toilet_no', models.CharField(max_length=30)),
                ('house_amenties', models.CharField(max_length=1500)),
                ('house_category', models.CharField(choices=[('ONE_BEDROOM', 'One Bedroom'), ('TWO_BEDROOM', 'Two Bedroom'), ('THREE_BEDROOM', 'Three Bedroom'), ('SELFCON', 'Selfcon')], max_length=80)),
                ('house_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agentuser')),
            ],
        ),
    ]
