# Generated by Django 6.0 on 2026-01-06 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_housemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='house_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
