# Generated by Django 6.0 on 2026-01-13 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_housemodel_created_at_housemodel_updated_at'),
        ('cities_light', '0012_city_translations_country_translations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.region'),
        ),
    ]
