# Generated by Django 6.0 on 2026-01-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_housemodel_country_housemodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='house_images',
            field=models.ImageField(upload_to='houses/'),
        ),
    ]
