# Generated by Django 6.0 on 2026-01-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_housemodel_house_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentuser',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
